Repository ASFHyP3/ingest-adapter, pull requests merged in 2025-02, with the labels that each got.

#5 add some boilerplate actions
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
Labels: bumpless

#9 add dockerfile and docker build action
  .github/workflows/test.yml
  plugin/Dockerfile
  requirements.txt
Labels: bumpless

#10 Add cloudformation for building app resources
  .github/actions/deploy/action.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  .github/workflows/static-analysis.yml
  cloudformation.yml
Labels: bumpless

#12 Update action.yml
  .github/actions/deploy/action.yml
Labels: bumpless

#11 update github action to create tag before release
  .github/workflows/release.yml
Labels: bumpless

#14 improve logging of unprocessed messages
  app/src/app.py
Labels: bumpless

#15 Load earthdata credentials from secrets manager
  app/src/app.py
  cloudformation.yml
  tests/test_app.py
  tests/test_plugin.py
Labels: bumpless

#16 fix topic arn environment variable name
  app/src/app.py
  tests/test_app.py
Labels: bumpless

#17 Fix static analysis workflow
  .github/workflows/static-analysis.yml
  requirements.txt
Labels: bumpless

#18 Move cloudformation file into app directory
  .github/actions/deploy/action.yml
  .github/workflows/static-analysis.yml
  app/cloudformation.yml
Labels: bumpless

#6 Update README.md
  README.md
Labels: bumpless

#21 Update lambda build dir
  app/cloudformation.yml
Labels: bumpless

#23 update README and ruff config
  README.md
  app/src/app.py
  pyproject.toml
Labels: bumpless

#24 fix image capitalization in README
  README.md
Labels: bumpless

#26 rename test action to also call out build; remove test requirement before building
  .github/workflows/test-and-build.yml
Labels: bumpless

#25 Use setup-micromamba for cfn-lint action
  .github/workflows/static-analysis.yml
Labels: bumpless

#19 Release v0.1.0
  .github/CODEOWNERS
  .github/actions/deploy/action.yml
  .github/dependabot.yml
  .github/workflows/changelog.yml
  .github/workflows/create-jira-issue.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  .github/workflows/labeled-pr.yml
  .github/workflows/release-template-comment.yml
  .github/workflows/release.yml
  .github/workflows/static-analysis.yml
  .github/workflows/test-and-build.yml
  CHANGELOG.md
  README.md
  app/cloudformation.yml
  app/requirements.txt
  app/src/app.py
  environment.yml
  plugin/Dockerfile
  plugin/requirements.txt
  plugin/src/plugin.py
  pyproject.toml
  requirements.txt
  tests/test_app.py
  tests/test_plugin.py
Labels: minor

#30 fix typo in stack names in deploy workflows
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
Labels: bumpless

#29 break tag and release into separate actions to resolve invalid GITHUB_REF error
  .github/workflows/release.yml
  .github/workflows/tag.yml
Labels: bumpless

#32 Release v0.1.1
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  CHANGELOG.md
Labels: patch

#35 Add 10 second delay to queue
  CHANGELOG.md
  app/cloudformation.yml
Labels: patch

#36 Release v0.1.2
  CHANGELOG.md
  app/cloudformation.yml
Labels: patch
